### ISSUE TITLE
BestAudioSource does not compile against VapourSynth doodle1 branch (ArchLinux)

### ISSUE THREAD

**Issue by sashka76** [vapoursynth/bestaudiosource#3]
BestAudioSource compile fails on 
"src/vapoursynth.cpp:89:115: error: ‘nfMakeLinear’ was not declared in this scope"

This is due to the following definition in "VapourSynth4.h":
typedef enum VSNodeFlags {
nfNoCache = 1
} VSNodeFlags;

The corresponding enum in master branch ("VapourSynth.h") is:
typedef enum VSNodeFlags {
nfNoCache = 1,
nfIsCache = 2,
nfMakeLinear = 4
} VSNodeFlags;

It has to compile against doodle1 branch because that's the branch that supports V4 plugins (afaik).

**Comment by myrsloik** [comment]
Development branches are not guaranteed to compile or work. At all. Ever.

**Comment by sashka76** [comment]
Sorry, I am new to this. What does it mean? That it is only guaranteed to compile at release points? What if there are no release points? It means it's never been ready for an official release?

**Comment by DJATOM** [comment]
@sashka76 
I managed to build audio plugin on linux and confirm that it works. 
You need to edit flags in plugin's source: vsapi->createAudioFilter(out, "Source", &D->AI, 1, BestAudioSourceGetFrame, BestAudioSourceFree, fmUnordered, **0**, D, core);
Tested with following script
```python3
import vapoursynth as vs
core = vs.core

audio = core.bas.Source("Darwins_Game_02_RUSUB_HD.mp4")
audio.set_output()
```
and it produced valid results:
```
djatom@atomch-server:~$ vspipe test_linux.vpy -p -c wav test.wav
Script evaluation done in 0.02 seconds
Output 68161152 samples in 108.43 seconds (628637.79 sps)
```

**Comment by sashka76** [comment]
Yes, it works for me, too (even if I use nfNoCache enum). So my "only" problem now is that VapourSynth V4 (doodle1 branch) does not work with FFMS2 (V3 work fine), producing a core dump almost immediately after trying to render the video (I see the video just for a second). I suppose if the problem was with libffms2.so plugin incompatibility, it would not open the video at all and give an error (like if I try to load BestAudioSource.so in VapourSynth V3). Anyway, that's nothing to do with BAS. Дякую, земляче!
